<?php

namespace app\modules\workspace\modules\personal;

use Yii;
use yii\base\Module;

/**
 * personal module definition class
 *
 */
class PersonalModule extends Module
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
        $this->controllerNamespace = 'app\modules\workspace\modules\personal\controllers';
    } // end function


    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
        Yii::$app->telemetry->ahoami()->save();
    } // end function

} // end class
